name: CI
on:
  push:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get -qy install qemu-user qemu-user-static
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          extra-platforms = aarch64-linux
          system-features = nixos-test benchmark big-parallel kvm
    - uses: actions/checkout@v3
    - run: nix flake check --print-build-logs --keep-going
